backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "data"
    label: "البيانات"
    files:
      - label: "المقالات"
        name: "articles"
        file: "articles.json"
        fields:
          - name: articles
            label: "قائمة المقالات"
            widget: "list"
            fields:
              - { label: "المعرف (رقم)", name: "id", widget: "number", value_type: "int" }
              - { label: "العنوان", name: "title", widget: "string" }
              - { label: "التصنيف", name: "category", widget: "select", options: ["أخبار", "وظائف", "الهجرة", "الطبخ", "تعليم السياقة", "رياضة", "أفلام ومسلسلات", "الربح من الإنترنت", "إصلاح الإلكترونيات"] }
              - { label: "التاريخ", name: "date", widget: "datetime" }
              - { label: "الصورة", name: "image", widget: "image" }
              - { label: "المحتوى (HTML)", name: "content", widget: "markdown" }
